### ISSUE TITLE
Naming convention does not match precedent specified in NIST SP 800-63A section 5.3.3.2

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#534] opened 2021-02-10 15:37 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.9.3, para. 4 Line 1023
 
**Comment (Include rationale for comment)**: Naming convention does not match precedent specified in NIST SP 800-63A section 5.3.3.2
 
**Suggested Change**: Supervised Remote In-Person Proofing
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment] 2021-02-25 20:04
Duplicate of #515

**Closed by jricher** 2021-02-25 20:04 UTC
Labels: Editorial, Public Comment, duplicate
