### ISSUE TITLE
Proofing to  be componentized and comprised of multiple independently-operated and owned business entities

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#267] opened 2021-02-01 20:12 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: NextgenID/STA

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1 Line 780
 
**Comment (Include rationale for comment)**: "...issuer-controlled station, remote location, trained operator at a central location" - SP 800-63-3/2.4 allows for CSP's to be componentized and comprised of multiple independently-operated and owned business entities.  Why should this not be extended to proofing?  Should also align with language in 2.7.1 line 788.

 
**Suggested Change**: …a station in a controlled-access environment that is connected to a remote location for remote operation by a trained trusted-provider.  The issuer may subscribe to or contract independently for trained operator services provided they are compliant with the NIST SP 800-63A specifications and guidance for SRIP.   See comment on line 25

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-03-09 18:27
suggest closing as it is a word-for-word duplicate of issue [548](https://github.com/usnistgov/FIPS201/issues/548).

**Closed** 2021-03-16 16:45 UTC
Labels: Enrollment, Public Comment, duplicate

**Comment by jglosx3** [comment] 2021-08-09 19:32
Duplicate of issue # 548
