### ISSUE TITLE
Missing an important UUID

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#446] opened 2021-02-09 03:04 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1840-1842
 
**Comment (Include rationale for comment)**: "The card UUID SHALL be encoded as a Uniform Resource Name (URN), as specified in Section 3 of [RFC 4122]."

Missing an important UUID.
 
**Suggested Change**: Cardholder (Person) UUID is critical for future activities in federation.  This data element should be mandatory, not optional.

"The card UUID SHALL be encoded as a Uniform Resource Name (URN), as specified in Section 3 of [RFC 4122].  The mandatory Person UUID, shall be encoded as a Uniform Resource Name (URN), as specified in Section 3 of [RFC 4122]."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment] 2021-03-25 18:48
Duplicate of #592

**Closed by jricher** 2021-03-25 18:48 UTC
Labels: PIV Card, Public Comment, duplicate
