### ISSUE TITLE
The usage of HTTPS for publishing CA certificates be prohibited in this standard to avoid the issues specified in Section 8 of RFC 5280

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#244] opened 2021-02-01 16:34 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: DoD

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 5.5.1 Line 2132
 
**Comment (Include rationale for comment)**: Does the specification of HTTP for publishing CA certificates preclude the usage of HTTPS?  Considering RFC 5280, it probably should.
 
**Suggested Change**: Suggest the following text be added, "the usage of HTTPS for publishing CA certificates be prohibited in this standard to avoid the issues specified in Section 8 of RFC 5280, one example of which is "relying parties ... MUST be prepared for the possibility that this will result in unbounded recursion."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment] 2021-03-12 15:09
Propose team discussion on language regarding usage of HTTPS for publishing CA certificates.

**Comment by jricher** [comment] 2021-04-01 17:18
duplicate of #243

**Closed by jricher** 2021-04-01 17:18 UTC
Labels: Other, Public Comment
