### ISSUE TITLE
DoD recommends incorporating language to support interoperability while maintaining the sovereignty of department and agency PKIs

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#242] opened 2021-02-01 16:31 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: DoD

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 5.4 Line 2111
 
**Comment (Include rationale for comment)**: "While DoD agrees with the removal of the term ""legacy PKI"" from FIPS-201, as currently written, FIPS-201 does not accurately address the distinction between Federal department and agency PKIs that are cross-certified with the Federal PKI and those that are operated under the Common Policy itself. Cross certification happens after the two PKIs are deemed comparable, but asserting a policy OID means that the certificate fully meets the requirements. DoD recommends incorporating language to support interoperability while maintaining the sovereignty of department and agency PKIs.

Specifically, DoD recommends continuation of the existing requirement that PIV-Authentication certificates assert the fpki-common-authentication policy, but not to add a new requirement for asserting common policy OIDs in signature and key management certificates."
 
**Suggested Change**: "DoD recommends replacing the current text with the following:

5.4 Agency PKIs

Note: this section was formerly entitled ""Legacy PKIs.""

Departments and agencies that operate their own agency CAs MAY specify their own policy OIDs in lieu of or in addition to [COMMON] policies in certificates associated with private keys for Digital Signing and Key Management certificates provided that the agency PKI is cross certified with the Federal Bridge CA or Federal Common Policy CA and the asserted agency policy OIDs map to the [COMMON] policy OIDs specified in 5.2.1."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment] 2021-03-12 15:20
Propose team discussion on using term 5.4 Agency PKIs.

**Comment by jricher** [comment] 2021-04-01 17:32
duplicate of #241

**Closed by jricher** 2021-04-01 17:32 UTC
Labels: Discussion Needed, Other, Public Comment
