### ISSUE TITLE
Remote identity proofing allows for safe continued Identity Proofing operations

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#259] opened 2021-02-01 19:15 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: Pespecta

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1 Line 781
 
**Comment (Include rationale for comment)**: "..goal..is to permit identity proofing in remote locations where it is not practical for them to travel.."
 
**Suggested Change**: Remote identity proofing allows for safe continued Identity Proofing operations (e.g., Social distancing)
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-04-27 15:49
This is close duplicate of #268. Suggest to close.

**Closed** 2021-04-27 17:30 UTC
Labels: Enrollment, Public Comment, duplicate
