### ISSUE TITLE
Sec 6.3.1 PAL concept is not consistent with SP800-63B.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#480] opened 2021-02-10 02:41 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 2430-2440
 
**Comment (Include rationale for comment)**: §6.3.1 PAL concept is not consistent with SP800-63B.  Recommend aligning FIPS 201-3 with ICAMSC Playbooks with SP800-63-B with PIV in E-PACS with GSA APL testing program with SP800-116, and industry capabilities.
 
**Suggested Change**: See comments to line 2430-2440.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment] 2021-04-07 23:29
Duplicate of #478

**Comment by regenscheid** [comment] 2021-04-13 17:16
Alignment with the new PAL

**Closed** 2021-04-13 17:17 UTC
Labels: Authentication, Noted, Public Comment

**Comment by regenscheid** [comment] 2021-08-13 14:38
Noted - The properties and requirements for physical access do not naturally align with logical access control. As such, the SP 800-63B authenticator assurance levels cannot be directly applied to physical access use cases.  

While Draft FIPS 201-3 initially specified Physical Assurance Levels, The final version of FIPS 201-3 instead merely describes the assurance characteristics of the applicable PIV authentication mechanisms for physical access use cases. Further guidance will be developed in a revision to NIST SP 800-116.
