### ISSUE TITLE
Leave the selection of a secure PIN to agency policies and procedures at the time of card activation

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#283] opened 2021-02-02 19:03 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: Dept. of Veteran Affairs

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 4.3.1 Line 2010 - 2012
 
**Comment (Include rationale for comment)**: Requiring the PIV card to compare the chosen PIN against commonly chosen values will warrant a card redesign, configuration changes to HSPD-12 systems, possibly slow down card performance and the deployment of a new card on the heels of the V8.1 card deployment.  This change will require more work across the Federal enterprise than the expected benefits of the change.
 
**Suggested Change**: Leave the selection of a secure PIN to agency policies and procedures at the time of card activation.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment] 2021-04-08 18:30
Duplicate of #589

**Closed by jglosx3** 2021-04-08 18:30 UTC
Labels: PIV Card, Public Comment, duplicate

**Comment by jglosx3** [comment] 2021-08-09 19:54
Duplicate of #493.
