### ISSUE TITLE
Add "through an on-card one-to-one comparison" after "PIV Card".

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#583] opened 2021-02-10 22:11 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.9.3, para. 2 Line 1001
 
**Comment (Include rationale for comment)**: This paragraph is about resetting a PIV card. If the PIV card needs to be reset, that means its PIN has been blocked due to too many consecutive failed verification attempts and therefore none of the biometric data on the card can be read.
 
**Suggested Change**: Add "through an on-card one-to-one comparison" after "PIV Card" on line 1003 in the sentence "… elicit a positive biometric verification decision when compared to biometric data records stored either on the PIV Card or in the PIV enrollment record."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment] 2021-03-18 16:30
see comment #584

Recommend accept.

**Comment by hferraio** [comment] 2021-03-19 19:22
suggest to decline.  The sentence in line 1000 describes a "reset" PIV card (i.e., rest was done), so biometric verification before handing the card back  works.

**Comment by jglosx3** [comment] 2021-07-21 19:43
We need to revisit this issue to confirm our intent was to decline based on the line number referenced (1003). We accepted a similar comment in issue #584 but it was on a different line.

**Comment by jricher** [comment] 2021-07-21 20:19
Wasn't the intent to mark this as a duplicate of an accepted issue, not to decline? That's what the tags had said before.

**Comment by gfiumara** [comment] 2021-07-22 17:26
This was a duplicate in principle, but from a different line. Both lines were resolved in #623.

**Closed** 2021-07-22 17:39 UTC
Labels: PIV Card, Public Comment, duplicate
