### ISSUE TITLE
Other Types of Issued Derived PIV Credential Digital Certificates: mobile device

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#572] opened 2021-02-10 21:40 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: [blank]
 
**Comment (Include rationale for comment)**: Other Types of Issued Derived PIV Credential Digital Certificates: Agencies may deliver Digital Signing Certificate, Encryption Certificates and Encryption Key History Keys along with Derived Credential Authentication Certificates for derived credentials issued to mobile devices.
 
**Suggested Change**: Agencies want to provide digital signing and encryption certs to mobile device such that emails can be signed and encrypted. Recommend reviewing and addressing these additional certificates and keys where they may apply in the draft standard, and also taking into consideration for the next version of SP 800-157.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment] 2021-03-02 01:04
Nearly a word-for-word duplicate of #332

**Closed** 2021-03-18 18:45 UTC
Labels: Derived PIV, Public Comment, duplicate
