### ISSUE TITLE
Authority and preferred specification of 800-63A for SRIP

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#275] opened 2021-02-01 20:48 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: NextgenID/STA

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1 Line 798, 799
 
**Comment (Include rationale for comment)**: SRIP is to be completed in complete alignment with 800-63A specifications/practices for SRIP -by explicitly stating rules within FIPS-201-3, this runs high risk of diverging from the authority and preferred specification of 800-63A for SRIP.
 
**Suggested Change**: Strike as not applicable.  This level of specification is not needed at the superior document level.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-03-16 19:26
Closing comment as it is a word-for-word duplicate of issue [556](https://github.com/usnistgov/FIPS201/issues/556).

**Closed by hferraio** 2021-03-16 19:26 UTC
Labels: Enrollment, Public Comment, duplicate

**Comment by jglosx3** [comment] 2021-08-09 19:45
Duplicate of issue #556
