### ISSUE TITLE
Clarification on language related to segmented enrollments

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#277] opened 2021-02-01 20:52 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: NextgenID/STA

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1 line 798, 799
 
**Comment (Include rationale for comment)**: Contrary to the notion of segmented enrollments

**Suggested Change**: Language implies a single session. This is different from a segmented process. Need clarification of the language. 

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-03-08 18:42
word-for-word duplicate to [558](https://github.com/usnistgov/FIPS201/issues/558). Suggest closing this one.

**Closed** 2021-03-16 19:46 UTC
Labels: Enrollment, Public Comment, duplicate

**Comment by jglosx3** [comment] 2021-08-09 19:49
Duplicate of #558
