### ISSUE TITLE
Fix formatting error

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#452] opened 2021-02-09 15:43 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 4.2.2 Line 1802-1804
 
**Comment (Include rationale for comment)**: Formatting error -  PIV Secure messaging key header is stuck on the end of PIV Card application administration key explanation
 
**Suggested Change**: Fix formatting error.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment] 2021-02-25 19:42
Duplicate of #205

**Closed by jricher** 2021-02-25 19:42 UTC
Labels: Editorial, Public Comment, duplicate
