### ISSUE TITLE
The market indicates a single chip dual-interface strategy.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#438] opened 2021-02-09 02:28 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1466-1467
 
**Comment (Include rationale for comment)**: "This Standard does not specify the number of chips used to support the mandated contact and contactless interfaces."
 
**Suggested Change**: The market clearly indicates a single chip dual-interface strategy.  Recommend delete for consistency with comments to 1369-1397.  In particular, PIV is implemented with a single, dual interface chip.  That is the key.  Adding 125KHz is outside the PIV domain and should remain that way.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-04-09 18:12
duplicate of #432 but for another line number.

**Closed** 2021-04-15 18:24 UTC
Labels: PIV Card, Public Comment, duplicate
