### ISSUE TITLE
PIN Checking on PIV Card

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#328] opened 2021-02-08 19:06 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: XTec., Inc

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 4.3.1 Line 2010
 
**Comment (Include rationale for comment)**: "PIN Checking on PIV Card: The draft states  ""The PIV Card SHALL compare the chosen PIN against a list of at least 10 commonly-chosen values (e.g., 000000, 123456) and require the choice of a different value if one of those is selected by the cardholder.""

XTec understands that card manufacturers find this requirement problematic to implement on the card."
 
**Suggested Change**: Delete the requirement for this to be enforced by the PIV Card.  If desired, add "The cardholder SHOULD avoid commonly chosen values"                                                                                                         
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment] 2021-04-08 18:34
Duplicate of #589

**Closed by jglosx3** 2021-04-08 18:34 UTC
Labels: PIV Card, Public Comment, duplicate
