### ISSUE TITLE
Re: PIN: Issue is not enforceable by the card.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#463] opened 2021-02-09 23:08 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 2010-2012
 
**Comment (Include rationale for comment)**: Issue is not enforceable by the card.
 
**Suggested Change**: Recommended language:
"The PIN should not be easily guessable. The PIN SHALL be a minimum of six digits and a maximum of eight digits in length. The PIV Card SHALL provide a policy that supports a list of chosen PINs (minimum of 100) that shall be rejected.  The PIV card SHALL enable the list of chosen PINs to be set by the CMS, enabling the Issuer to control their list of chosen PINs that should be rejected.  This PIN policy shall be discoverable and defined in [NIST SP 800-73]."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment] 2021-04-07 23:14
#589 seems to be a more complete treatment of this issue, so let's call this a duplicate of that one.

**Closed** 2021-04-08 18:26 UTC
Labels: Authentication, Public Comment, duplicate
