### ISSUE TITLE
Supervised Remote In-Person Proofing SHALL meet the requirements and criteria in NIST SP 800-63A

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#271] opened 2021-02-01 20:42 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: NextgenID/STA

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1 Line 797
 
**Comment (Include rationale for comment)**: SRIP is defined as Supervised Remote Proofing in Appendix A of NIST SP 800-63-3 as – A remote identity proofing process that employs physical, technical, and procedural measures that provide sufficient confidence that the remote session can be considered equivalent to a physical, in-person identity proofing process.  If the 800-63-3 definition holds than it is discordant with the draft FIPS 140-3 language “SHALL be monitored by staff at the station location…” and footnote 9 "...where staff can see the station while performing other duties."
 
**Suggested Change**: Supervised Remote In-Person Proofing SHALL meet the requirements and criteria in NIST SP 800-63A.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-03-01 16:47
Suggest to close as it is a duplicate of issue [552](https://github.com/usnistgov/FIPS201/issues/552)

**Closed** 2021-03-16 17:59 UTC
Labels: Enrollment, Public Comment, duplicate

**Comment by jglosx3** [comment] 2021-08-09 19:38
Duplicate of issue #552
