### ISSUE TITLE
What is meant by "monitored" and "staff" and for what purpose?

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#273] opened 2021-02-01 20:45 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: NextgenID/STA

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1 Line 796, 797, footnote 9
 
**Comment (Include rationale for comment)**: The introduction of draft statements requiring monitoring by staff at the station location are antithesis to the benefits and intent of SRIP
 
**Suggested Change**: What is meant by "monitored" and "staff" and for what purpose?  Contend that the draft content be deprecated or further clarified as it is superceded by NIST SP 800-63A 5.3.3.2 describing attributes exceeding the confidence and security attained by local operators/staff.  
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-03-01 16:32
Suggest to close as it is a dupliate of issue [554](https://github.com/usnistgov/FIPS201/issues/554).

**Comment by hferraio** [comment] 2021-03-01 22:50
Suggest to close this issue as it is covered in [580](https://github.com/usnistgov/FIPS201/issues/580).

**Closed** 2021-03-16 19:17 UTC
Labels: Enrollment, Public Comment, duplicate

**Comment by jglosx3** [comment] 2021-08-09 19:43
Duplicate of #580
