### ISSUE TITLE
IS OCC allowed here?

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#403] opened 2021-02-09 00:34 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1025-1029
 
**Comment (Include rationale for comment)**: Is OCC allowed here?
 
**Suggested Change**: What modalities?  Vendors support both fingerprint and iris for on-card-comparison.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-03-26 19:11
suggest to decline.  Currently, OCC is specified for fingerprints only. We could include _"Other OCC modalities, as specified in [SP 800-73], MAY be used."_ However, more support for other modality needs to be voiced by department and agencies in order to justify inclusion in SP 800-73 in future revisions.  Note that including additional modalities should be weight against GSA's Test Program's effort to reduce the number of options offered and thus reduce complexity.

**Comment by regenscheid** [comment] 2021-04-29 17:40
Duplicate of #584

**Closed by regenscheid** 2021-04-29 17:40 UTC
Labels: Discussion Needed, Enrollment, Public Comment

**Comment by regenscheid** [comment] 2021-04-29 17:47
OCC is currently only specified for fingerprint in SP 800-76 and SP 800-73.  Additional modalities could be considered when those documents are updated.  However, this is not a topic for FIPS 201.
