### ISSUE TITLE
As written, this method does not confirm if the card is revoked.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#473] opened 2021-02-10 02:27 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 2223-2237
 
**Comment (Include rationale for comment)**: As written, this method does not confirm if the card is revoked.
 
**Suggested Change**: Recommend adding "Some characteristics…" to this section.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-04-07 15:49
Suggest to note. This is specified just a few lines above  - in line 2208.

**Comment by hferraio** [comment] 2021-04-07 17:34
duplicate of #472 -except it t is on BIO-A vs BIO text. and has a  different suggested change.  

We could point to 6.2.1 for characteristics, but may not be necessary as the section on BIO-A  is a sub-section of 6.2.1 and characteristics are just 2 page up.

**Comment by regenscheid** [comment] 2021-04-08 18:44
This is already addressed in Section 6.2.1.

**Closed** 2021-04-08 18:45 UTC
Labels: Authentication, Public Comment, duplicate
