### ISSUE TITLE
Recommend defining CVP

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#573] opened 2021-02-10 21:43 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.2 Line 568
 
**Comment (Include rationale for comment)**: Continuous Vetting Program:  Section 2.2 (Credentialing Requirements)  states "This determination SHALL be recorded in the PIV enrollment record to reflect PIV eligibility for the PIV cardholder and, if applicable, their enrollment in the Continuous Vetting Program."
Continuous Vetting Program is only mentioned once in the draft and not defined.
 
**Suggested Change**: Recommend defining CVP, and expand on its impact/significance to Credentialing Requirements and any other relevant requirements.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-02-26 18:56
This is a duplicate of issue # [333](https://github.com/usnistgov/FIPS201/issues/333). Suggest to close.

**Closed** 2021-03-19 13:51 UTC
Labels: Enrollment, Public Comment, duplicate
