### ISSUE TITLE
Restore Legacy PKI to FIPS 201-3 to ensure clarity and permit continued use of alternative digsig

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#454] opened 2021-02-09 15:47 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 5.4 Line 2111-2114
 
**Comment (Include rationale for comment)**: This imposes a fundamental change on agency implementations, particularly for organizations that operate their own PKI domains and do not use COMMON policy OIDs for their digsig or kmk certificates.   This section previously stated "This specification imposes no requirements on digital signature or key management certificates issued by legacy PKIs."  In addition, COMMON Policy takes its requirements from FIPS 201-3 for the implementation of PIV certificates.  This is necessary because at the end of the day FIPS 201 trumps COMMON Policy.  If FIPS 201-3 does not allow something, there is no avenue or justification for FPKI/COMMON policy to do so. 
 
**Suggested Change**: "Restore Legacy PKI to FIPS 201-3 to ensure clarity and permit continued use of alternative digsig and kmk policy OIDs. Alternatively, revise language on lines 2091-2097 to replace ""SHALL"" with ""SHOULD"" and add a footnote to indicate that agencies that operate legacy PKI may choose to use alternate policy OIDs for digsig and kmk.  "
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment] 2021-02-25 16:13
Propose team discussion.

**Comment by jglosx3** [comment] 2021-03-24 19:23
Recommend reject based on prior discussions on legacy PKI

**Comment by regenscheid** [comment] 2021-04-06 17:07
Duplicate of #241

**Closed** 2021-04-06 17:07 UTC
Labels: Other, Public Comment
