### ISSUE TITLE
"PIV enrollment records SHOULD include the following data: ….."

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#354] opened 2021-02-08 20:57 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 650-670
 
**Comment (Include rationale for comment)**: "PIV enrollment records SHOULD include the following data: ….."

How can federated interoperability take place, if there are not a minimum set of ""shall"" requirements in the enrollment record? 

 
**Suggested Change**: Recommend breaking the sub-bullets up into "shall" statements, AND "should" statements. Determined the required data set needed for a base level "enrollment record" for all agencies to achieve, in order to trust the credential issued. The "should" statements would be ones to achieve before the next release of FIPS 201 (i.e., 201-4). 

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment] 2021-03-08 18:23
Propose team discussion.

**Comment by regenscheid** [comment] 2021-04-01 18:27
Duplicate of #368

**Closed by regenscheid** 2021-04-01 18:27 UTC
Labels: Other, Public Comment, duplicate
