### ISSUE TITLE
Why is PAL being introduced?

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#479] opened 2021-02-10 02:38 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 2430-2440
 
**Comment (Include rationale for comment)**: Why is PAL being introduced? 800-63 addresses this 
 
**Suggested Change**: See comments to line 2430-2440.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment] 2021-04-07 23:29
Duplicate of #478

**Closed** 2021-04-13 17:09 UTC
Labels: Authentication, Public Comment, duplicate
