### ISSUE TITLE
"PIV cardholder interacts with these components for PIV card management activities..."

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#415] opened 2021-02-09 01:12 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1205-1207
 
**Comment (Include rationale for comment)**: "The PIV cardholder interacts with these components to gain physical or logical access to the desired federal resource."
 
**Suggested Change**: Should be "The PIV cardholder interacts with these components for PIV card management activities, and to gain physical or logical access to authorized federal resource."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment] 2021-04-15 18:22
duplicate of #420

**Closed by jricher** 2021-04-15 18:22 UTC
Labels: PIV Card, Public Comment
