### ISSUE TITLE
Maybe use OCC language

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#402] opened 2021-02-08 22:35 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1003-1009
 
**Comment (Include rationale for comment)**: …inspect documents…
 
**Suggested Change**: See comment for 880-885

Maybe use OCC language in 1014-1015.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment] 2021-03-03 20:17
Propose team discussion. Cannot make sense of of comment or suggested change.

**Comment by hferraio** [comment] 2021-03-19 16:36
Closing this comment as the issue is represented in and duplicate of #392 (except that comment applies to a different line number).

**Closed by hferraio** 2021-03-19 16:36 UTC
Labels: Other, Public Comment, duplicate

**Comment by jglosx3** [comment] 2021-08-09 19:10
Duplicate of #392 (except that comment applies to a different line number).
