### ISSUE TITLE
Naming convention does not match precedent specified in NIST SP 800-63A section 5.3.3.2

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#262] opened 2021-02-01 19:56 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: NextgenID/STA

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: See spreadsheet attached below, same error for several locations. 
 
**Comment (Include rationale for comment)**: Naming convention does not match precedent specified in NIST SP 800-63A section 5.3.3.2
 
**Suggested Change**: "Supervised Remote In-Person Proofing" or similar harmonized language should be used across all documents.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment] 2021-02-01 20:04
Attaching spreadsheet with location information for requested naming convention update. 
[FIPS 201- 3-draft-comment-NextgenID Naming Convention Updates.xlsx](https://github.com/usnistgov/FIPS201/files/5906461/FIPS.201-.3-draft-comment-NextgenID.Naming.Convention.Updates.xlsx)

**Comment by hferraio** [comment] 2021-03-04 20:52
suggest to close - as it is a duplicate of [515](https://github.com/usnistgov/FIPS201/issues/515)

**Closed** 2021-04-22 16:22 UTC
Labels: Enrollment, Public Comment, duplicate

**Comment by jglosx3** [comment] 2021-08-09 19:27
Duplicate of  #515
