### ISSUE TITLE
Supervised Remote In-Person Proofing SHALL meet the requirements and criteria in NIST SP 800-63A

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#265] opened 2021-02-01 20:09 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: NextgenID/STA

**Organization Type (see below for codes)**: 2- Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1 Line 795
 
**Comment (Include rationale for comment)**: SRIP is simply a special use case (remote operator v. local operator) of the already established IAL3 In-Person Identity Proofing as meticulously defined in SP 800 63-3 and SP 800-63A (5.3.3.2) Supervised Remote In-Person Proofing, wherein all informative and normative compliance specifications are detailed.

 
**Suggested Change**: Supervised Remote In-Person Proofing SHALL meet the requirements and criteria in NIST SP 800-63A.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-03-16 19:05
Closing this comment as it is a word-for-word duplicate of [546](https://github.com/usnistgov/FIPS201/issues/546).

**Closed by hferraio** 2021-03-16 19:05 UTC
Labels: Enrollment, Public Comment, duplicate

**Comment by jglosx3** [comment] 2021-08-09 19:29
Duplicate of #546
