### ISSUE TITLE
Is the prohibition on HTTP protocol or the method of delivery?

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#532] opened 2021-02-10 15:35 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Sec. 5.5.1, page 68, Para. 2: Line 2134-2138
 
**Comment (Include rationale for comment)**: Is the prohibition on the HTTP protocol or the method of delivery? Is this intended to include delivery over private connections supported by HTTPS or other secure tunnels such as VPN or SSH? Is the prohibition related to publishing in public directory rather than use in authenticating to a Government system from the public portion of the Internet.
 
**Suggested Change**: Clarify.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment] 2021-02-24 16:29
Propose team discussion

**Comment by jricher** [comment] 2021-04-01 17:17
duplicate of #243

**Closed by jricher** 2021-04-01 17:17 UTC
Labels: Other, Public Comment
