### ISSUE TITLE
Recommend clarification to differentiate from required proofing resources (i.e., trained operators)

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#272] opened 2021-02-01 20:44 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: NextgenID/STA

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1 Line 797
 
**Comment (Include rationale for comment)**: The introduction of draft statements requiring monitoring by staff at the station location are antithesis to the benefits and intent of SRIP

 
**Suggested Change**: If the intent is security of persons/objects, the clarification must be made to differentiate from required proofing resources (i.e., trained operators).  

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-03-03 17:20
Suggest to close as it is a word-by-word duplicate of [260](https://github.com/usnistgov/FIPS201/issues/260)

**Closed** 2021-03-16 18:42 UTC
Labels: Enrollment, Public Comment, duplicate

**Comment by jglosx3** [comment] 2021-08-09 19:42
Duplicate of #260 and issue #533
