### ISSUE TITLE
Missing Title: "Secure Messaging Key Establishment Key"

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#587] opened 2021-02-10 22:18 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 4.2.2 Line 1803
 
**Comment (Include rationale for comment)**: The optional asymmetric private key that supports key establishment for secure
messaging and card authentication for physical access is NOT the PIV Card Application Administration Key. A title is missing above this paragraph to separate from Admin key.
 
**Suggested Change**: Add the following title above this paragraph: "Secure Messaging Key Establishment Key"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-04-02 20:27
duplicate of #452

**Closed** 2021-04-13 17:50 UTC
Labels: Authentication, Public Comment, duplicate
