### ISSUE TITLE
New requirement for the PIV Card

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#287] opened 2021-02-02 21:07 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: Treasury 

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 6.2.5
 
**Comment (Include rationale for comment)**: "NIST added the following requirements:
(1) A maximum of 10 consecutive PIN retries SHALL be permitted unless a lower limit is imposed by the department or agency.
(2) The PIN SHALL be a minimum of six digits in length. 
(3) The PIV Card SHALL compare the chosen PIN against a list of at least 10 commonly-chosen values (e.g., 000000, 123456) and require the choice of a different value if one of those is selected by the cardholder.
We checked with the USAccess card vendor (Idemia) to determine if the v8.1 PIV Cards comply with these requirements, because otherwise a new card version will have to be developed/deployed. We were told that requirements 1 and 2 are supported, but not 3."

 
**Suggested Change**: The new requirement for the PIV Card to "compare the chosen PIN against a list of at least 10 commonly-chosen values (e.g., 000000, 123456) and require the choice of a different value if one of those is selected by the cardholder" is not supported by the current USAccess PIV Cards. This would require the vendor to develop a new PIV Card version and issuers to replace these cards. In addition, we are concerned that this requirement would slow down the performance of the card without adding any significant level of security. Instead of this being added as a requirement, we think this should be a recommendation to the cardholders when selecting a PIN.”  There is little return on investment for this huge cost. Newly issue Cards should fall under this new requirement. 

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment] 2021-04-08 18:32
Duplicate of #598

**Closed by jglosx3** 2021-04-08 18:32 UTC
Labels: PIV Card, Public Comment, duplicate

**Comment by jglosx3** [comment] 2021-08-09 19:57
Duplicate of #598
