### ISSUE TITLE
"…individual's identity account within the Enterprise IDMS."

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#353] opened 2021-02-08 20:55 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 646
 
**Comment (Include rationale for comment)**: "...cardholder’s PIV account."
 
**Suggested Change**: This should be "…individual's identity account within the Enterprise IDMS."  It truly is not a "PIV account," as the identity account may receive a PIV, CIV, PIV-I, Derived PIV.  These are benefits of having the identity account and being vetted for an appropriate credential (the benefit) based on need.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment] 2021-02-16 19:35
See also #341

**Comment by currydm** [comment] 2021-03-08 18:22
Propose team discussion.

**Comment by regenscheid** [comment] 2021-04-01 18:23
Duplicate of #341

**Closed by regenscheid** 2021-04-01 18:23 UTC
Labels: Other, Public Comment, duplicate
