### ISSUE TITLE
2.7.1 Footnote 9 not needed at the superior document level as full specification already exists in 800-63A

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#279] opened 2021-02-01 20:55 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: NextgenID/STA

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1 Footnote 9
 
**Comment (Include rationale for comment)**: Not required by 800-63A nor is it warranted as long as video surveillance, security and tamper detection is implemented 

 
**Suggested Change**: Strike as not applicable, Specification is not needed at the superior document level as full specification already exists in 800-63A  Sec 5.3.3.1 and 5.3.3.2.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-03-03 20:07
Suggest to close as issue is represented (duplicate of) [58](https://github.com/usnistgov/FIPS201/issues/580)

**Closed** 2021-03-16 20:03 UTC
Labels: Enrollment, Public Comment, duplicate

**Comment by jglosx3** [comment] 2021-08-09 19:50
Duplicate of issue #580 and issue #550
