### ISSUE TITLE
Guessable/Identifiable PINs

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#327] opened 2021-02-08 19:04 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: XTec., Inc

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 4.3.1 Line 2008
 
**Comment (Include rationale for comment)**: "Guessable/Identifiable PINs: The draft states  ""The PIN should not be easily guessable or otherwise individually identifiable in nature (e.g., part of a Social Security Number or phone number). ""

This is written in the passive voice, obscuring how the control is enforced (i.e. by the informed cardholder), and that issuers have a responsibility to provide guidance as part of cardholder training."
 
**Suggested Change**: Change the statement to the active voice.  “The cardholder SHOULD NOT choose a PIN that is easily guessable or otherwise individually identifiable in nature (e.g., part of a Social Security Number or phone number).”                                                                                                                                                          
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-04-09 18:16
suggest closing as it is addressed in #589

**Comment by jricher** [comment] 2021-04-15 17:50
duplicate of #589

**Comment by regenscheid** [comment] 2021-04-15 17:50
Duplicate of #589

**Closed** 2021-04-15 17:50 UTC
Labels: PIV Card, Public Comment, duplicate
