### ISSUE TITLE
Naming convention does not match precedent specified in NIST SP 800-63A section 5.3.3.2

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#535] opened 2021-02-10 15:38 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: Appendix E, p. 115 Line NA
 
**Comment (Include rationale for comment)**: Naming convention does not match precedent specified in NIST SP 800-63A section 5.3.3.2
 
**Suggested Change**: Supervised Remote In-Person Proofing
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-03-04 20:49
suggest to close - as it is a duplicate of [515](https://github.com/usnistgov/FIPS201/issues/515)

**Closed** 2021-03-26 17:21 UTC
Labels: Enrollment, Public Comment, duplicate
