### ISSUE TITLE
Process non-specific, implicit attribution to 800-63 is undefined

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#266] opened 2021-02-01 20:10 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: NextgenID/STA

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1 Line 779
 
**Comment (Include rationale for comment)**: Process non-specific, implicit attribution to 800-63 is undefined

 
**Suggested Change**: …MAY use the Supervised Remote In-Person Proofing process per the guidelines specified in NIST SP 800-63A for the issuance of PIV Cards.    Suggest creating a highlevel section that combines items in Sect 2.7.1 line 779 -819  and reference SP 800- 63 and 63A for specific details.  

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-03-16 16:35
word-for-word duplicate - closing this issue as it is represented in [547](https://github.com/usnistgov/FIPS201/issues/547).

**Closed by hferraio** 2021-03-16 16:35 UTC
Labels: Enrollment, Public Comment, duplicate

**Comment by jglosx3** [comment] 2021-08-09 19:31
Duplicate of issue #547
