### ISSUE TITLE
Recommend policy be changed to single chip dual-interface cards.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#422] opened 2021-02-09 01:35 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1227
 
**Comment (Include rationale for comment)**: "...with one or more embedded Integrated Circuit Chips (ICC)…"
 
**Suggested Change**: Recommend this policy be changed to single chip dual-interface cards.  "...with one embedded Integrated Circuit Chip (ICC)…"

This policy enables hybrid cards with 125KHz which is inherently insecure and not part of SP800-116 anymore.  The PIV in E-PACS does not support this configuration, and the GSA APL does not test/affirm it as PIV compliant."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-04-09 18:59
duplicate of #432 - although for another line number.

**Closed** 2021-04-15 18:24 UTC
Labels: PIV Card, Public Comment, duplicate
