### ISSUE TITLE
Delineated requirements specified in NIST SP 800-63A 5.3.3.2

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#270] opened 2021-02-01 20:41 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: NextgenID/STA

**Organization Type (see below for codes)**: 2 - Industry 
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1 Line 789
 
**Comment (Include rationale for comment)**: Obviated by delineated requirements specificed in NIST SP 800-63A 5.3.3.2
 
**Suggested Change**: Contend that the draft content be deprecated as  it should be further defined by NIST SP 800-63A 5.3.3 describing attributes exceeding the confidence and security attained by local operators/staff. Remove from FIPS 201-3.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-03-16 17:51
Closing this comment as it is a word-for-word duplicate of issue [551](https://github.com/usnistgov/FIPS201/issues/551).

**Closed by hferraio** 2021-03-16 17:51 UTC
Labels: Enrollment, Public Comment, duplicate

**Comment by jglosx3** [comment] 2021-08-09 19:37
Duplicate of issue #551
