### ISSUE TITLE
Unique Identifiers to Promote Federal Interoperability

### ISSUE THREAD

**Issue by ssatyapal123** [usnistgov/FIPS201#301] opened 2021-02-04 21:34 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: N/A

**Organization Type (see below for codes)**: 4
 
**Reference (Include section/paragraph or pdf line number)**:
4.2.4. PIV Unique Identifiers

**Comment (Include rationale for comment)**: 
 The VA is adopting the DoD's Electronic Health Record system which currently uses the DoD EDI-PI as the unique identifier.  The current plan is to provision EDI-PIs to all VA personnel (~730K) requiring access to the joint system, as well as VA patients (~9million) that far outnumber the DoD patient population.  This is not a sustainable solution as it makes VA dependent on DoD to provision and manage identity attributes of VA personnel and patients.  Had there been a federally unique identifier, this situation would not have occurred.  A more sustainable solution for such situations is to embed a federally unique identifier on the PIV card itself that allows for an ecosystem of identity providers to perform delegated authentication and authorization services without the need for creating new "unique" identifiers.

**Suggested Change**: 
 Include language in the FIPS 201-3 that mandates using the last 16 digits of the Federal Agency Smart Card Number (FASCN) to uniquely identify the cardholder for the Executive branch and other federal partners.  The DoD and VA construction of the PIV Authentication certificate Subject Alternative Name will include an Other Name:Principal Name field constructed by concatenating the last 16 digits of the FASCN with "@federal agency abbreviation" (e.g., last 16 digits of FACSN@mil or last 16 digits of FASCN@va).  DMDC and VA can then use this construction to aid with interoperability and onboarding new federal entities to the Federal Electronic Health Record system.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment] 2021-03-11 19:33
Duplicate of #239

**Closed by jricher** 2021-03-11 19:33 UTC
Labels: Other, Public Comment
