### ISSUE TITLE
Mechanical / physical barriers and electronic (camera) monitoring without staff physically located at station

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#261] opened 2021-02-01 19:20 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: Perspecta

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1 Line 796
 
**Comment (Include rationale for comment)**: The introduction of draft statements requiring monitoring by staff at the station location are antithesis to the benefits and intent of SRIP
 
**Suggested Change**: Monitoring by staff can be adequately performed with the same level of security with mechanical / physical barriers and electronic (camera) means without staff phycially located at the station. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-03-31 17:56
Closing issue as it is a duplicate of #580

**Closed by hferraio** 2021-03-31 17:56 UTC
Labels: Enrollment, Public Comment
