### ISSUE TITLE
Sec 2.7.1 Line 786 should match verbiage from NIST SP 800-63A 5.3.3.2

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#269] opened 2021-02-01 20:39 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: NextgeID/STA

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1 Line 786
 
**Comment (Include rationale for comment)**: should match verbiage from NIST SP 800-63A 5.3.3.2
 
**Suggested Change**: …to achive comparable levels of confidence and security to in-person events." The draft attribution of "closely duplicate" is superfluous and erroneous as the use of SRIP technology can enhance and improve standard in-person proofing practices.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-03-16 17:47
Closing this comment as it is a word-for-word duplicate of [550](https://github.com/usnistgov/FIPS201/issues/550).

**Closed** 2021-03-16 17:49 UTC
Labels: Enrollment, Public Comment, duplicate

**Comment by jglosx3** [comment] 2021-08-09 19:36
Duplicate of issue #550
