### ISSUE TITLE
"station SHALL be maintained in a controlled-access environment and SHALL be monitored ...'

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#377] opened 2021-02-08 21:19 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 796-797
 
**Comment (Include rationale for comment)**: "The station SHALL be maintained in a controlled-access environment and SHALL be monitored by staff at the station location while it is being used."
 
**Suggested Change**: This bullet should be struck and operational deployment issues should be identified in SP 800-79.  This may include privacy barriers, as well as deployment in controlled access areas.  SP 800-63A already requires tamper resistance and the scene camera to protect the act of enrollment.  Adding staff to monitor the enrollment does not improve the security of the enrollment based on SP 800-63A requirements.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-03-01 22:58
Suggest to close this issue as it is covered in [580](https://github.com/usnistgov/FIPS201/issues/580).

**Closed** 2021-03-26 18:29 UTC
Labels: Enrollment, Public Comment, duplicate

**Comment by jglosx3** [comment] 2021-07-28 21:20
Duplicate of issue #580.
