### ISSUE TITLE
PIV Identitifiers for Interoperability and federation

### ISSUE THREAD

**Issue by TimSchmoyer** [usnistgov/FIPS201#300] opened 2021-02-04 20:44 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: N/A

**Organization Type (see below for codes)**: 4
 
**Reference (Include section/paragraph or pdf line number)**: 4.2.2.1 PIV Authentication Key (1836-1839), 4.2.4 PIV Unique Identifiers (1971-1989), 6.2.3.1 Authentication with the PIV Authentication Certificate Credential (PKI-AUTH) (2272-2274), 7.3 Benefits of Federation (2504-2506)
 
**Comment (Include rationale for comment)**: 

Interoperability and federation between different federal departments and agencies require PIV cardholder identitifiers that are unique within the PIV (and PIV-I) identity management space. This is a long-standing mission need and gap also related to implementing FPKI and PIV-I (Federal and Non-Federal Issuers) logical access control using the PIV Authentication certificate and implementing identity provider (IdP) services such as the Backend Attribute Exchange Broker demonstrated by DHS and DoD.

**Suggested Change**: 

Mandate that the last 16 digits of the Federal Agency Smart Card Number (FASCN)  uniquely identify the cardholder for the Executive branch and other federal partners (congress, courts, state, local, territory, tribe, etc.) conform with existing ISO, NIST FIPS/SP attributes for PIV, PIV-I, PIV-C, etc., and its location as a cardholder identifier field for both the card and PIV authentication certificate.  The DoD and VA construction of the PIV Authentication certificate Subject Alternative Name will include an Other Name:Principal Name field constructed by concatenating the last 16 digits of the FASCN with "@federal agency abbreviation" (e.g., last 16 digits of FACSN@mil or last 16 digits of FASCN@va).  DMDC and VA intend to use this construction to aid with interoperability and onboarding new federal entities to the Federal Electronic Health Record system.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment] 2021-03-11 19:29
Duplicate of #239

**Closed by jricher** 2021-03-11 19:29 UTC
Labels: Other, Public Comment
