### ISSUE TITLE
"PIV Card PIN Reset for Activation"

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#398] opened 2021-02-08 22:11 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 989-990
 
**Comment (Include rationale for comment)**: The title of the section relates to "activation reset," yet the language starts out by discussing "PIN" on a PIV Card "may need to be reset." 
 
**Suggested Change**: Recommend the title of the section be updated to "PIV Card PIN Reset for Activation."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment] 2021-02-25 19:39
Duplicate of #218 (part 1)

**Closed by jricher** 2021-02-25 19:39 UTC
Labels: Editorial, Public Comment, duplicate
