### ISSUE TITLE
"A CHUID MAY also include a Person UUID…"

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#442] opened 2021-02-09 02:40 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1760
 
**Comment (Include rationale for comment)**: "A CHUID MAY also include a Cardholder UUID…""

A CHUID may include a CHUUID. 
 
**Suggested Change**: "A CHUID MAY also include a Person UUID…"

This makes it clear it is a Person Identifier, much like the PI in the FASC-N.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment] 2021-04-12 14:24
Recommend decline.  we don't define person UUID in the version of the standard.

**Comment by hferraio** [comment] 2021-04-12 14:51
I think it would be confusing at this point to change names. We have the Person ID in the CHUID's FASC-N already. So calling this one Person UUID (similarly) is confusing. Also:  several documents (SP 800-73 SP 800-79,, SP 800-85A/B, SP 800-116, GSA APL reader test procedural documents,  GSA annual card data model compliance program, etc) would have to change and trickle down.  Changing name may in itself create confusion (is this a new identifier? and what happened with the cardholder UUID with tag 0x37 in the CHUID)?

**Comment by regenscheid** [comment] 2021-04-20 17:15
Duplicate of #358

**Closed by regenscheid** 2021-04-20 17:15 UTC
Labels: PIV Card, Public Comment, duplicate
