### ISSUE TITLE
There should be a single reserved area for the chip/contact plate per 7810

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#439] opened 2021-02-09 02:31 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1473-1479
 
**Comment (Include rationale for comment)**: "The reason for the recommended reserved areas is that placement of the embedded contactless ICC module may vary between manufacturers, and there are constraints that prohibit printing over the embedded contactless module. The PIV Card topography provides flexibility for placement of the embedded module, either in the upper right corner or in the lower portion. Printing restrictions apply only to the area where the embedded module is located."
 
**Suggested Change**: There should be a single reserved area for the chip/contact plate per 7810.  This standard really should no longer encourage 125KHz for PACS or other dual-chip designs.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-04-09 18:49
duplicate of #432 but on another line #.

**Closed** 2021-04-15 18:50 UTC
Labels: PIV Card, Public Comment, duplicate
