### ISSUE TITLE
"...and what data was collected, since the creation of that record."

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#356] opened 2021-02-08 20:59 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 652
 
**Comment (Include rationale for comment)**: "...and what data was collected."
 
**Suggested Change**: Recommend:   Recommend this be codified explicitly in SP 800-156.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment] 2021-03-03 20:54
Line 652 deals will Enrollment record data. Assigning to Hildy/Andy.

**Comment by regenscheid** [comment] 2021-04-01 18:29
Duplicate of #368

**Closed by regenscheid** 2021-04-01 18:29 UTC
Labels: Other, Public Comment, duplicate
