### ISSUE TITLE
Language regarding timeframe when the CHUID authentication mechanism must no longer be used 

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#286] opened 2021-02-02 21:06 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: Treasury

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 4.2.1
 
**Comment (Include rationale for comment)**: "NIST added text to this section pertaining to the removal of the CHUID authentication mechanism and detailed the remaining purpose/use of the CHUID. They also added specifications for the Cardholder UUID and clarified that the content signing certificate SHALL NOT expire before the expiration of the card authentication certificate.
NIST should specify the timeframe when the CHUID authentication mechanism must no longer be used or change this to allow Agencies to make a risk based decision about when to stop using it."

 
**Suggested Change**: "NIST should specify the timeframe when the CHUID authentication mechanism must no longer be used or change this to allow Agencies to make a risk based decision about when to stop using it. This specific timeframe will allow for proper and systematic bugeting resulitng in greater compliance."

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-04-07 15:24
duplicate of #493.

**Closed** 2021-04-08 17:44 UTC
Labels: Authentication, Public Comment, duplicate
