### ISSUE TITLE
Sec 2.7.1 Line 813-819 Include reference to 800-63A 5.3.3.1

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#280] opened 2021-02-01 20:56 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: NextgenID/STA

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1 Line 813-819
 
**Comment (Include rationale for comment)**: Include reference to 800-63A 5.3.3.1
 
**Suggested Change**: "..per the criteria defined in [SP 800-76] and [SP 800-63A 5.3.3.1 and ]..Sec 5.3.3.1 and 5.3.3.2.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-03-16 20:10
Closing this issue as it is a word-for-word duplicate of [561](https://github.com/usnistgov/FIPS201/issues/561).

**Closed by hferraio** 2021-03-16 20:10 UTC
Labels: Enrollment, Public Comment, duplicate

**Comment by jglosx3** [comment] 2021-08-09 19:51
Duplicate of #561
