### ISSUE TITLE
Recommend 201 require 800-63 IAL3 and Tier 1

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#503] opened 2021-02-10 14:11 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Sec. 2.7, Pg. 13, Para. 1: Line 705-707
 
**Comment (Include rationale for comment)**: The reference to Identity Proofing in SP 800-63 is the government guidelines for Identity Proofing. It is unclear what the “tailoring process” in intended to mean here. SP800-63-3a does not refer to “tailoring” except in regards to NIST SP 800-53 controls and none in regards to Identity Proofing requirements.

Proposed language is confusing. It essentially promotes separate requirements for the two documents and tries to explain/rationalize the differences. Recommend NIST merge the requirements rather than have separate requirements.
 
**Suggested Change**: Recommend 201 require 800-63 IAL3 and Tier 1. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-04-20 16:36
Suggest to note.  FIPS 201-3 does follow SP 800-63. It is essentially a profile of SP 800-63  while also  applying compensating controls as allowed and described in SP 800-63. Merging of the two document is not possible, as SP 800-63 is broader than just PIV.

**Comment by jricher** [comment] 2021-04-29 17:23
related to (but not duplicate of) #508

**Comment by regenscheid** [comment] 2021-04-29 17:26
Decline. Per the discussions at the Business Requirements Meeting, we believe the tailored issuance process described in Section 2.7 PIV provides a sufficient level of assurance. We believe the on-boarding process and the background investigation mitigate the risks from not meeting all of the documentary evidence requirements from-63A.

**Closed by regenscheid** 2021-04-29 17:26 UTC
Labels: Discussion Needed, Enrollment, Public Comment
