### ISSUE TITLE
The PIN should not be easily guessable or otherwise individually identifiable in nature

### ISSUE THREAD

**Issue by andyatyeo** [usnistgov/FIPS201#206] opened 2021-01-04 16:19 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: Intercede

**Organization Type (see below for codes)**: 2
 
**Reference (Include section/paragraph or pdf line number)**: section 4.3.1 "Activation by cardholder" line 2008
 
**Comment (Include rationale for comment)**: 
Quote - "The PIN should not be easily guessable or otherwise individually identifiable in nature (e.g., part of a Social Security Number or phone number)" 
This is a very sensible line in its intent, but it is problematic in implementation. Ultimately it is the cardholder that chooses the PIN, although the allowable values is limited by the card itself and the software between the user and the card.
The card itself clearly cannot enforce this rule (as it does not know the users SSN or phone number and since these are only examples, there is no concrete rule that it can implement)
The software between the user and card (e.g. the card issuance system) - could try to do something to implement this rule, but it is problematic:
* it is woolly what the matching rules are/what is allowed or disallowed (e.g. SSN)
* in order for software to implement the check of the PIN against this data which is personally identifiable information (PII) either the PIN would need to be sent to the backend system to check it is allowed (bad idea to distribute the PIN), or additional PII (e.g. phone number, SSN) would need to be sent to the client for the check on the client (unnecessary additional distribution of PII).
* The example of checking against SSN implies distribution of SSN, and possibly even additional capture of SSN in software that may not be storing the SSN already. sp800-122 (regarding PII) on page ES-2 is stating that "OMB M-07-168 specifically requires agencies to: .. Establish a plan to eliminate the unnecessary collection and use of SSNs"
* There are many bits of software that could cause a PIN to be chosen for the PIV card - not just the issuance system, but PIN change could be performed on a disconnected system as only the current PIN is needed to authorize a PIN change. A disconnected system would be unable to enforce such a rule that the PIN does not match e.g. SSN/phone number, as it would have no access to that info (and nor should it)

**Suggested Change**: 
I believe the intent of this statement is that the cardholder is ultimately responsible (and in fact the only part of the system that can enforce this rule), although as written it implies that it is a problem for software to solve (which as written above could cause more problems than it solves).
Therefore I suggest changing to:
"The cardholder should not choose a PIN that is easily guessable or otherwise individually identifiable in nature (e.g., part of a Social Security Number or phone number)."

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by adricasti** [comment] 2021-01-30 19:43
Agree with the suggested edit and the fact that enforcing rules that depend on data external to the card is problematic.  Maybe extend the examples to: (e.g. a repetition of a single digit like '000000', an ordered sequence like '123455', part of a Social Security Number, phone number, date of birth or other data that could easily be known about the cardholder)

**Comment by regenscheid** [comment] 2021-04-08 18:22
Duplicate of #589

**Closed** 2021-04-08 18:26 UTC
Labels: PIV Card, Public Comment
