### ISSUE TITLE
DO NOT deprecate the SYM-CAK key or the SYM-CAK authentication mechanism

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#326] opened 2021-02-08 19:03 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: XTec, Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 4.2.2.3 / 6.2.4 Line 1865 / 2316
 
**Comment (Include rationale for comment)**: "FIPS 201-3 should NOT deprecate either the SYM-CAK key or the SYM-CAK authentication mechanism.
There are 3 reasons:
1. SYM-CAK, used in combination with PKI-CAK (“Plan A/Plan B”), offers Federal Departments and Agencies greater benefits than PKI-CAK used alone.
2. Deprecating SYM-CAK will stifle agency use and vendor innovation, to the disadvantage of Federal Departments and Agencies
3. NIST’s published criteria for “deprecated and removed features” do not justify deprecating SYM-CAK.

A separate  document has been submitted on GitHub with detailed explanations for each of these reasons for NOT deprecating SYM-CAK."
 
**Suggested Change**: "DO NOT deprecate the SYM-CAK key or the SYM-CAK authentication mechanism."

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment] 2021-04-08 16:33
Recommend Reject

**Comment by jricher** [comment] 2021-04-08 17:13
duplicate of #207

**Closed by jricher** 2021-04-08 17:13 UTC
Labels: PIV Card, Public Comment
