### ISSUE TITLE
 Further define "monitored by staff"

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#379] opened 2021-02-08 21:22 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS
**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line796-797
 
**Comment (Include rationale for comment)**: "...SHALL be monitored by staff at the station location while it is being used.9"
 
**Suggested Change**: "This requires double the personnel to use SRIP, essentially defeating the purpose of the centralized Enrollment Official.

In the DHS context, an intent was to field SRIP stations within the airport environment, or in DHS facility hallways, which are unlikely to have staff or E-PACS video available to monitor the station.

Recommend adding requirements to further define ""monitored by staff."" Could the Issuer put agreements in place with GSA and other agencies who provide security guard staff at entrance points to federally controlled facilities, who could meet this requirement? Could the Issuer put agreements in place with the E-PACS that has video monitoring for the station?  These agreements extend the audit boundary for enrollment and may not be sustainable."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-03-01 22:57
Suggest closing this issue as it is covered in issue [580](https://github.com/usnistgov/FIPS201/issues/580).

**Closed** 2021-03-26 18:23 UTC
Labels: Enrollment, Public Comment, duplicate

**Comment by jglosx3** [comment] 2021-08-09 16:34
Duplicate of issue #580
