### ISSUE TITLE
Examples are missing from Table 4.1

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#585] opened 2021-02-10 22:15 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**:  2 - Industry

**Reference (Include section/paragraph or pdf line number)**: 4.1.4.1, table 4.1 Line 1530
 
**Comment (Include rationale for comment)**: Examples are missing from the table; one of them is displayed in the page footer.
 
**Suggested Change**: Fix the display of table 4.1
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment] 2021-02-25 20:37
Duplicate of #218 (part 4/5)

**Closed by jricher** 2021-02-25 20:37 UTC
Labels: Editorial, Public Comment, duplicate
