### ISSUE TITLE
Specify a specific date when magnetic stripe feature will be discontinued.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#495] opened 2021-02-10 03:24 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 1.3.4 pg. 4: Line 425
 
**Comment (Include rationale for comment)**: In a manner similar to other FIPS there should be a date-certain upon which the removed feature will be discontinued.
 
**Suggested Change**: Specify a specific date when magnetic stripe feature will be discontinued.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment] 2021-03-18 16:55
Declined.  It is implied the magnetic strip deprecation goes into effect when this version of the standard goes into effect.

**Comment by hferraio** [comment] 2021-03-19 19:49
Suggest to add: As per line 417-419, a gradual phase out is proposed that gives department and agencies amble of time for a phase out.  It states: _Deprecated features MAY continue to be used but SHOULD be phased out in future systems since the feature will likely
be removed in the next revision of the Standard._ 

Note: Magnetic strips are under the 'deprecated' category and not under the "removed' category as the CHUID authentication mechanism is. Only features categorized as 'removed'  will have to adhere to a specific end date.

**Comment by jricher** [comment] 2021-04-01 18:47
duplicate of #387

**Closed by jricher** 2021-04-01 18:47 UTC
Labels: Discussion Needed, PIV Card, Public Comment
