### ISSUE TITLE
CHUID (Card Holder Unique Identifier) Publish Timeline

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#290] opened 2021-02-02 21:15 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: Department of Energy

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 1745
 
**Comment (Include rationale for comment)**: Section 4.2.1 requires that the CHUID (Card Holder Unique Identifier) no longer be used for physical access card authentication.

 
**Suggested Change**: Given the size and expense of complying with this requirement, NIST must either publish a timeline for implementing and give agencies time to allocate funds or allow agencies to make risk-based decisions about when they will comply. 

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment] 2021-04-07 22:40
Looks like another duplicate of #493

**Closed** 2021-04-08 17:43 UTC
Labels: Authentication, Public Comment, duplicate

**Comment by jglosx3** [comment] 2021-08-09 19:59
Duplicate of #493
