### ISSUE TITLE
HHS requests guidance added for adequate transition timelines to deplete the existing inventory

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#292] opened 2021-02-02 21:20 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: Health and Human Services (HHS)

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 4.3.1 Line 2010 - 2012
 
**Comment (Include rationale for comment)**: "The reference as written suggests the PIV Card edge will enforce this new mandatory feature for PIV Activation, as well as PIN resets.  This new requirement will make existing card stock incompatible once the Standard and dependent NIST Special Publications become effective. HHS requests guidance added for adequate transition timelines to deplete the existing inventory of previously purchased products, time for new products to become available, and for PIV systems to be updated.

Rationale: There are multiple technological solutions that make up the ability to create, update and use PIN numbers for PIV credentials (e.g., the PIV card, Middleware, and Card Issuance Systems). We believe some agencies maintain PIN data differently, such as requiring a PIN change immediately after personalization to prevent Card Management System (CMS) from having record of the initial PIN.  Additionally, many agencies have purchased APL PIV card stock in bulk as agencies plan months and years ahead for their expected volume of card holders. "
 
**Suggested Change**: "Return of implementation schedule guidance

10. Implementation Schedule.
This Standard mandates the implementation of new PIV Card features. To comply with FIPS 201-3, all new and replacement PIV Cards shall be issued with the mandatory PIV Card features no later than 12 months after the effective date of this Standard or of the depending new or revised NIST Special Publications.  

Accreditations of PIV Card issuers (PCIs) that occur 12 months after the effective date of this Standard shall be in compliance with FIPS 201-3."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment] 2021-03-12 14:55
Propose team discussion on implementation schedule.

**Comment by regenscheid** [comment] 2021-04-01 17:42
Revisit once we resolve other issues that impact PIV card requirements and features.

**Comment by regenscheid** [comment] 2021-04-01 18:09
Duplicate of #339

**Closed by regenscheid** 2021-04-01 18:09 UTC
Labels: Discussion Needed, Other, Public Comment
