### ISSUE TITLE
Specify the timeframe when the CHUID authentication mechanism must no longer be used

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#288] opened 2021-02-02 21:09 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: Treasury

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 6.2.5
 
**Comment (Include rationale for comment)**: "NIST removed the CHUID as an authentication mechanism in this version of the Standard. The CHUID data element itself, however, has not been removed and continues to be mandatory as it supports other PIV authentication mechanisms. 
NIST should specify the timeframe when the CHUID authentication mechanism must no longer be used or change this to allow Agencies to make a risk based decision about when to stop using it."

 
**Suggested Change**: "See row above
The new requirement for the PIV Card to ""compare the chosen PIN against a list of at least 10 commonly-chosen values (e.g., 000000, 123456) and require the choice of a different value if one of those is selected by the cardholder"" is not supported by the current USAccess PIV Cards. This would require the vendor to develop a new PIV Card version and issuers to replace these cards. In addition, we are concerned that this requirement would slow down the performance of the card without adding any significant level of security. Instead of this being added as a requirement, we think this should be a recommendation to the cardholders when selecting a PIN.”"

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by regenscheid** [comment] 2021-04-08 17:43
Duplicate of #493

**Closed** 2021-04-08 17:43 UTC
Labels: Authentication, Public Comment, duplicate
