### ISSUE TITLE
Section 4.3.1 limits the number of failed attempts at establishing a PIN

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#291] opened 2021-02-02 21:16 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: Department of Energy

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 1997
 
**Comment (Include rationale for comment)**: Section 4.3.1 limits the number of failed attempts at establishing a PIN during card activation to 10. Also requires enforcement of mechanisms to prevent the applicant from selecting unsecure PINs.

 
**Suggested Change**: Per HSPD-12 vendor (Idemia), this would require a new PIV card creation and deployment. Current measures for secure PIN creation and could possibly slow down card performance. Recommend agencies enforce this as a process when cardholder is selecting a PIN.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-04-12 17:28
duplicate of #597

**Comment by regenscheid** [comment] 2021-04-15 17:29
Decline.  The requirement limits the number of failed attempts to unlock a a card to use the PIV Auth key, and perform other functions that require the card to be unlocked.  It does not refer to the number of attempts to initially set the PIN.

**Closed by regenscheid** 2021-04-15 17:29 UTC
Labels: Declined, PIV Card, Public Comment
