### ISSUE TITLE
PIN Checking on the CMS/Middleware

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#329] opened 2021-02-08 19:07 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: XTec., Inc

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 4.3.1 Line 2010
 
**Comment (Include rationale for comment)**: "PIN Checking on the CMS/Middleware: The draft states  ""The PIV Card SHALL compare the chosen PIN against a list of at least 10 commonly-chosen values (e.g., 000000, 123456) and require the choice of a different value if one of those is selected by the cardholder.""

There has been discussion within industry that this control could be enforced elsewhere, such as in middleware or within the issuer's card management system.  However, such an implementation would allow the control to be circumvented easily.  Anytime after post issuance, a cardholder could merely change the PIN using an alternate capabaility that does not enforce the control, e.g. the default Windows 10 PIN change feature allows unrestricted PIN changes (other than PIN-length enforcement by the PIV card). To see how this is easily accomplished, we refer you to:  https://pivkey.zendesk.com/hc/en-us/articles/204375395-How-do-I-change-the-user-PIN- . PIN-changes can also be accomplished using other available online tools and middleware.  This control can ONLY be consistently and effectively implemented by the card, and not by any other component of the system. 
"
 
**Suggested Change**: "DO NOT change this requirement so that some other component of the system (e.g. the middleware or CMS) is responsible for implementing the control to check against a list of commonly-chosen values.
Delete the requirement. It is not practicle to implement on the PIV Card nor within the CMS/middleware."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment] 2021-04-08 18:33
Duplicate of #589

**Closed by jglosx3** 2021-04-08 18:33 UTC
Labels: PIV Card, Public Comment, duplicate

**Comment by jglosx3** [comment] 2021-07-21 19:52
Accept in principle: New text will eliminate the need for card to check agaist blacklist of keys. Card Management processes will provide guidance to cardholders on PIN selection.
