### ISSUE TITLE
Provide some context/definition for the term adjudicative entity

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#371] opened 2021-02-08 21:11 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.9.1 Line 909
 
**Comment (Include rationale for comment)**: Use of the term "adjudicative entity" - this term is not defined in the glossary.  
 
**Suggested Change**: Provide some context/definition for the term adjudicative entity.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment] 2021-03-15 19:39
Closing this issue as it is covered in  [388](https://github.com/usnistgov/FIPS201/issues/388)

**Closed** 2021-03-15 19:39 UTC
Labels: Enrollment, Public Comment, duplicate

**Comment by jglosx3** [comment] 2021-08-09 16:20
Duplicate of issue #388
