### ISSUE TITLE
Overhaul of PACS readers and the CHUID technology

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#293] opened 2021-02-02 21:22 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: Health and Human Services (HHS)

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 6.2.5 Line 2342 - 2343
 
**Comment (Include rationale for comment)**: "Request to keep CHUID as a deprecated feature for layered access control implementations.  This would allow agencies to design cost effective implementations that require PKI authentication at the perimeter access points but allow persons to move between areas with equal or less interior security requirements utilizing existing readers and relying infrastructure.

Rationale: Many agencies, HHS included, still heavily rely on CHUID for PACS authentication in their facilities. An overhaul of PACS readers and the CHUID technology is a massive overtaking, requiring funding approval from agency leadership, effective and efficient project management, and the ability to balance this project with other key initiatives."

 
**Suggested Change**: The CHUID authentication mechanism is no longer allowed under FIPS-201 as an authenticator for entry into secured access control points.  As the CHUID authentication mechanism provides LITTLE or NO assurance in the identity of the cardholder, CHUID MAY only be used after successful authentication at the perimeter of a layered access control system to allow persons to move between interior areas having equal or less security requirements.  It is expected that this limited use of the CHUID authentication mechanism will be removed from this Standard at the next five-year revision.  Agencies SHALL plan a full transition away from CHUID as an authentication method across their facilities.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment] 2021-04-07 22:42
Duplicate of #215 from NASA; same use case.

**Closed** 2021-04-08 17:24 UTC
Labels: Authentication, Public Comment, duplicate
