### ISSUE TITLE
"Relying Party", "Relying System" and "Relying Subsystem": Suggest deciding on a single term. 

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#570] opened 2021-02-10 19:24 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: General
 
**Comment (Include rationale for comment)**: "Relying Party", "Relying System" and "Relying Subsystem": These terms are used for what appears to be the same thing, and/or are not specifically defined or distinguished from each other. 
 
**Suggested Change**: Suggest deciding on a single term. Note that SP 800-63-3/63A/63B/63C use "relying party".
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment] 2021-02-24 15:40
Propose team discussion

**Comment by jricher** [comment] 2021-03-12 16:49
Duplicate of #331

**Closed** 2021-03-17 18:21 UTC
Labels: Other, Public Comment, duplicate
