### ISSUE TITLE
Personalization (physical and logical)

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#429] opened 2021-02-09 01:53 UTC
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1323
 
**Comment (Include rationale for comment)**: "Personalization (physical and logical)…"
 
**Suggested Change**: Recommend "Personalization (printed and electrical)…" because it is more than logical information.  Also supports physical.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment] 2021-04-15 18:32
duplicate of #424

**Closed by jricher** 2021-04-15 18:32 UTC
Labels: PIV Card, Public Comment, duplicate
